# Generated by Django 4.2.25 on 2025-10-08 08:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='05xxxxxxxx', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم جوال سعودي بصيغة 05xxxxxxxx', regex='^05\\d{8}$')])),
                ('father_name', models.CharField(blank=True, help_text='اسم الأب (اختياري)', max_length=50)),
                ('grandpa_name', models.CharField(blank=True, help_text='اسم الجد (اختياري)', max_length=50)),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('accountant', 'Accountant'), ('cashier', 'Cashier')], db_index=True, default='donor', max_length=20)),
                ('national_number', models.CharField(help_text='10 أرقام', max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يتكون من 10 أرقام', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['role'], name='Management__role_0e0ff6_idx'), models.Index(fields=['phone'], name='Management__phone_e300a7_idx'), models.Index(fields=['user'], name='Management__user_id_ed8a3e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('national_number',), name='uq_profile_national_number'),
        ),
        migrations.AddConstraint(
            model_name='profile',
            constraint=models.UniqueConstraint(fields=('phone',), name='uq_profile_phone'),
        ),
    ]
