# Generated by Django 4.2.25 on 2025-10-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('donor', 'Donor'), ('accountant', 'Accountant'), ('cashier', 'Cashier'), ('system_admin', 'System Admin')], db_index=True, default='donor', max_length=20),
        ),
    ]
