# Generated by Django 4.2.25 on 2025-10-15 10:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('request', 'Request'), ('password_change', 'Password Change'), ('other', 'Other')], db_index=True, max_length=32)),
                ('entity', models.CharField(db_index=True, max_length=100)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['action', 'entity'], name='Management__action_80b6e3_idx'), models.Index(fields=['ts'], name='Management__ts_8ca76e_idx')],
            },
        ),
    ]
