# Generated by Django 4.2.25 on 2025-10-16 08:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0003_auditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=50)),
                ('grand_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], db_index=True, max_length=10)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('none', 'غير متعلم'), ('primary', 'ابتدائي'), ('middle', 'متوسط'), ('high', 'ثانوي')], max_length=20)),
                ('health_status', models.CharField(blank=True, choices=[('good', 'سليم'), ('sick', 'مريض')], max_length=10)),
                ('disease', models.CharField(blank=True, help_text='اسم المرض (إن وجد)', max_length=100)),
                ('type_disease', models.CharField(choices=[('none', 'لا يوجد'), ('chronic', 'مستعصي'), ('temporary', 'غير مستعصي')], default='none', max_length=20)),
                ('type_housing', models.CharField(blank=True, choices=[('own', 'ملك'), ('rent', 'إيجار'), ('family', 'عائلي')], max_length=10)),
                ('housing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('beneficiary_rank', models.CharField(blank=True, help_text='ترتيب اليتيم', max_length=20)),
                ('number_of_beneficiary_in_family', models.PositiveIntegerField(default=1, help_text='عدد ايتام الأسرة', validators=[django.core.validators.MinValueValidator(1)])),
                ('national_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='رقم الهوية يجب أن يتكون من 10 أرقام', regex='^\\d{10}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(blank=True, help_text='المتبرّع (كفيل) المسؤول', limit_choices_to={'role': 'donor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiaries', to='Management.profile')),
            ],
            options={
                'verbose_name': 'Beneficiary',
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='Management__last_na_738078_idx'), models.Index(fields=['gender'], name='Management__gender_57e923_idx'), models.Index(fields=['donor'], name='Management__donor_i_a82c81_idx')],
            },
        ),
    ]
