# Generated by Django 4.2.25 on 2025-10-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0004_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='health_status',
            field=models.CharField(blank=True, choices=[('healthy', 'سليم'), ('sick', 'مريض')], max_length=10),
        ),
    ]
