# Generated by Django 4.2.25 on 2025-10-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0005_alter_beneficiary_health_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='education_level',
            field=models.CharField(blank=True, choices=[('child', 'طفل'), ('kg', 'روضة'), ('p1', 'أول ابتدائي'), ('p2', 'ثاني ابتدائي'), ('p3', 'ثالث ابتدائي'), ('p4', 'رابع ابتدائي'), ('p5', 'خامس ابتدائي'), ('p6', 'سادس ابتدائي'), ('m1', 'أول متوسط'), ('m2', 'ثاني متوسط'), ('m3', 'ثالث متوسط'), ('h1', 'أول ثانوي'), ('h2', 'ثاني ثانوي'), ('h3', 'ثالث ثانوي')], max_length=20),
        ),
    ]
