# Generated by Django 4.2.25 on 2025-10-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_alter_beneficiary_education_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='type_housing',
            field=models.CharField(blank=True, choices=[('own', 'ملك'), ('rent', 'إيجار'), ('share', 'مشترك')], max_length=10),
        ),
    ]
