# Generated by Django 4.2.25 on 2025-10-27 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0007_alter_beneficiary_type_housing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم البرنامج الأساسي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('total_donation_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='إجمالي مبلغ التبرع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المتبقي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'برنامج أساسي',
                'verbose_name_plural': 'البرامج الأساسية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم البرنامج الفرعي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المخصص')),
                ('spent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المصروف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('main_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_programs', to='Management.mainprogram', verbose_name='البرنامج الأساسي')),
            ],
            options={
                'verbose_name': 'برنامج فرعي',
                'verbose_name_plural': 'البرامج الفرعية',
                'ordering': ['-created_at'],
            },
        ),
    ]
