# Generated by Django 4.2.25 on 2025-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0008_mainprogram_subprogram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='spent_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ المصروف'),
        ),
    ]
