# Generated by Django 4.2.25 on 2025-11-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0009_alter_subprogram_spent_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الاشتراك (ريال)')),
                ('duration_months', models.PositiveSmallIntegerField(verbose_name='المدة (بالأشهر)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'خطة دفع',
                'verbose_name_plural': 'إدارة الدفعات',
            },
        ),
    ]
