# Generated by Django 4.2.25 on 2026-07-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_paymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainprogram',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
    ]
