# Generated by Django 4.2.25 on 2026-07-14 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0011_mainprogram_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiarySponsorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='بداية الكفالة')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='نهاية الكفالة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='تم الإسناد بواسطة')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_history', to='Management.beneficiary', verbose_name='المستفيد')),
                ('donor', models.ForeignKey(limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_history', to='Management.profile', verbose_name='الكافل')),
            ],
            options={
                'verbose_name': 'سجل كفالة',
                'verbose_name_plural': 'سجل الكفالات',
                'ordering': ['-start_date', '-id'],
            },
        ),
    ]
