# Generated by Django 4.2.25 on 2026-08-04 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_beneficiarysponsorhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainprogram',
            name='remaining_amount',
        ),
    ]
