# Generated by Django 4.2.25 on 2026-08-09 05:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0013_remove_mainprogram_remaining_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='allocated_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المخصص'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='main_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_programs', to='Management.mainprogram', verbose_name='البرنامج الرئيسي'),
        ),
        migrations.AlterField(
            model_name='subprogram',
            name='spent_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المصروف'),
        ),
    ]
