# Generated by Django 4.2.25 on 2025-12-04 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0010_paymentplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProgramDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sub_program', 'من رصيد البرنامج الفرعي'), ('beneficiary', 'من رصيد المستفيد')], default='sub_program', max_length=20, verbose_name='مصدر الصرف')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher_number', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='رقم السند')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.subprogram')),
            ],
            options={
                'verbose_name': 'أمر صرف برنامج فرعي',
                'verbose_name_plural': 'أوامر صرف البرامج الفرعية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SubProgramDisbursementLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Management.beneficiary')),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='Accounting.subprogramdisbursement')),
            ],
            options={
                'verbose_name': 'تفاصيل صرف مستفيد',
                'verbose_name_plural': 'تفاصيل صرف المستفيدين',
            },
        ),
        migrations.CreateModel(
            name='MainToSubProgramAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('main_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_allocations', to='Management.mainprogram', verbose_name='البرنامج الرئيسي')),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_allocations', to='Management.subprogram', verbose_name='البرنامج الفرعي')),
            ],
            options={
                'verbose_name': 'تحويل من رئيسي لفرعي',
                'verbose_name_plural': 'تحويلات من الرئيسي للفروع',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='اكتب رقم السند يدوياً', max_length=20, null=True, unique=True)),
                ('date', models.DateField(verbose_name='تاريخ السند')),
                ('invoice_type', models.CharField(choices=[('general_donation', 'تبرع عام'), ('financial_sponsorship', 'كفالة مالية')], max_length=32, verbose_name='نوع الفاتورة')),
                ('receipt_kind', models.CharField(choices=[('receipt', 'سند قبض'), ('payment', 'سند صرف')], default='receipt', max_length=16, verbose_name='نوع السند')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'نقدًا'), ('bank_transfer', 'تحويل بنكي'), ('bank_card', 'بطاقة بنكية')], max_length=20, null=True, verbose_name='وسيلة القبض')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'فاتورة / سند',
                'verbose_name_plural': 'الفواتير / السندات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GeneralDonationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_from', models.CharField(blank=True, max_length=100, verbose_name='البنك المحوّل منه')),
                ('from_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب المحوّل منه')),
                ('to_account_number', models.CharField(blank=True, max_length=50, verbose_name='الحساب المحوّل عليه')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('amount_in_words', models.CharField(blank=True, help_text='يتم توليدها أو كتابتها يدويًا في النموذج.', max_length=255, verbose_name='المبلغ كتابة')),
                ('supporter_name', models.CharField(blank=True, max_length=150, verbose_name='اسم الداعم')),
                ('supporter_phone', models.CharField(blank=True, max_length=20, verbose_name='جوال الداعم')),
                ('supporter_national_number', models.CharField(blank=True, help_text='يمكن استخدامها لاحقًا لربط الداعم ككافل في النظام.', max_length=20, verbose_name='هوية الداعم')),
                ('invoice', models.OneToOneField(limit_choices_to={'invoice_type': 'general_donation'}, on_delete=django.db.models.deletion.CASCADE, related_name='general_donation', to='Accounting.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تفاصيل تبرع عام',
                'verbose_name_plural': 'تفاصيل التبرعات العامة',
            },
        ),
        migrations.CreateModel(
            name='FundToMainProgramAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('main_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_allocations', to='Management.mainprogram', verbose_name='البرنامج الرئيسي')),
            ],
            options={
                'verbose_name': 'تخصيص من الصندوق لبرنامج رئيسي',
                'verbose_name_plural': 'تخصيصات الصندوق للبرامج الرئيسية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FundEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('general_donation_income', 'دخل تبرع عام'), ('sponsorship_income', 'دخل كفالة مالية'), ('program_expense', 'صرف على برنامج'), ('transfer_to_beneficiary', 'تحويل لرصيد مستفيد'), ('adjustment', 'تعديل رصيد')], max_length=40, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب للدخل، سالب للصرف.', max_digits=12, verbose_name='المبلغ')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_entries', to='Management.beneficiary', verbose_name='المستفيد (إن وجد)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_entries', to=settings.AUTH_USER_MODEL, verbose_name='تم تسجيلها بواسطة')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_entries', to='Accounting.invoice', verbose_name='السند المرتبط')),
                ('main_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_entries', to='Management.mainprogram', verbose_name='البرنامج الرئيسي (إن وجد)')),
                ('sub_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_entries', to='Management.subprogram', verbose_name='البرنامج الفرعي (إن وجد)')),
            ],
            options={
                'verbose_name': 'حركة رصيد الجمعية',
                'verbose_name_plural': 'حركات رصيد الجمعية',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FinancialSponsorshipInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_custom_plan', models.BooleanField(default=False, help_text="إذا كانت الخطة 'أخرى' يسمح بإدخال مبلغ ومدة يدويًا.", verbose_name='خطة مخصّصة (أخرى)')),
                ('custom_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='مبلغ الكفالة (فعلي)')),
                ('custom_duration_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدة الكفالة بالأشهر (فعلية)')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية الكفالة')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية الكفالة')),
                ('bank_from', models.CharField(blank=True, max_length=100, verbose_name='البنك المحوّل منه')),
                ('from_account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب المحوّل منه')),
                ('to_account_number', models.CharField(blank=True, max_length=50, verbose_name='الحساب المحوّل عليه')),
                ('invoice', models.OneToOneField(limit_choices_to={'invoice_type': 'financial_sponsorship'}, on_delete=django.db.models.deletion.CASCADE, related_name='financial_sponsorship', to='Accounting.invoice', verbose_name='الفاتورة')),
                ('payment_plan', models.ForeignKey(blank=True, help_text='يتم تعريفها من مدير النظام في جدول خطط الدفعات.', null=True, on_delete=django.db.models.deletion.PROTECT, to='Management.paymentplan', verbose_name='نوع الكفالة (خطة الدفع)')),
                ('sponsor', models.ForeignKey(help_text='يجب أن يكون نوعه DONOR في النظام.', limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_invoices', to='Management.profile', verbose_name='الكافل')),
            ],
            options={
                'verbose_name': 'تفاصيل كفالة مالية',
                'verbose_name_plural': 'تفاصيل الكفالات المالية',
            },
        ),
        migrations.CreateModel(
            name='FinancialSponsorshipAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ المخصص')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التخصيص')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_allocations', to='Management.beneficiary', verbose_name='المستفيد')),
                ('sponsorship_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='Accounting.financialsponsorshipinvoice', verbose_name='سند الكفالة المالية')),
            ],
            options={
                'verbose_name': 'تخصيص كفالة مالية',
                'verbose_name_plural': 'تخصيصات الكفالات المالية',
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب = زيادة في رصيد المستفيد، سالب = تخفيض/صرف.', max_digits=12, verbose_name='المبلغ')),
                ('type', models.CharField(choices=[('sponsorship_allocation', 'رصيد كفالة'), ('adjustment', 'تعديل رصيد'), ('expense', 'صرف تحت برنامج')], max_length=32, verbose_name='نوع الحركة')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='وصف الحركة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ إنشاء الحركة')),
                ('allocation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='balance_entry', to='Accounting.financialsponsorshipallocation', verbose_name='تخصيص الكفالة')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balance_entries', to='Management.beneficiary', verbose_name='المستفيد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_balance_entries', to=settings.AUTH_USER_MODEL, verbose_name='تم تسجيلها بواسطة')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_balance_entries', to='Management.subprogram', verbose_name='البرنامج الفرعي')),
            ],
            options={
                'verbose_name': 'حركة رصيد مستفيد',
                'verbose_name_plural': 'حركات أرصدة المستفيدين',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
