# Generated by Django 4.2.25 on 2025-12-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundentry',
            name='voucher_number',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='رقم السند'),
        ),
    ]
