# Generated by Django 4.2.25 on 2025-12-16 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0010_paymentplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Accounting', '0002_fundentry_voucher_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintosubprogramallocation',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'تحويل رئيسي إلى فرعي', 'verbose_name_plural': 'تحويلات رئيسي إلى فرعي'},
        ),
        migrations.AlterField(
            model_name='maintosubprogramallocation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FundReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('beneficiary', 'محفظة مستفيد'), ('main_program', 'ميزانية برنامج رئيسي'), ('sub_program', 'ميزانية برنامج فرعي')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب = حجز، سالب = تحرير حجز', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='رقم السند / مرجع العملية', max_length=50)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_reservations', to='Management.beneficiary')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('main_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_reservations', to='Management.mainprogram')),
                ('sub_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_reservations', to='Management.subprogram')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
