# Generated by Django 4.2.25 on 2025-12-29 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0010_paymentplan'),
        ('Accounting', '0003_alter_maintosubprogramallocation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundreservation',
            options={},
        ),
        migrations.CreateModel(
            name='BeneficiarySupportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='موجب فقط (قيمة ما استفاد به المستفيد من محفظة برنامج).', max_digits=12, verbose_name='مبلغ الدعم')),
                ('voucher_number', models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='رقم سند الصرف')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_entries', to='Management.beneficiary', verbose_name='المستفيد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='beneficiary_support_entries', to=settings.AUTH_USER_MODEL)),
                ('disbursement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_entries', to='Accounting.subprogramdisbursement', verbose_name='أمر الصرف')),
                ('main_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_entries', to='Management.mainprogram', verbose_name='البرنامج الرئيسي')),
                ('sub_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_entries', to='Management.subprogram', verbose_name='البرنامج الفرعي')),
            ],
            options={
                'verbose_name': 'دعم مستفيد من برنامج',
                'verbose_name_plural': 'دعم المستفيدين من البرامج',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
