# Generated by Django 4.2.25 on 2026-07-14 11:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0012_beneficiarysponsorhistory'),
        ('Accounting', '0004_alter_fundreservation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/sponsorship/')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship_reports', to='Management.profile')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Management.profile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
