# Generated by Django 4.2.25 on 2026-08-04 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0013_remove_mainprogram_remaining_amount'),
        ('Accounting', '0005_sponsorshipreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogramdisbursement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='subprogramdisbursement',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_program_disbursements', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='subprogramdisbursement',
            name='notes',
            field=models.CharField(blank=True, max_length=255, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='subprogramdisbursement',
            name='sub_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='Management.subprogram', verbose_name='البرنامج الفرعي'),
        ),
        migrations.AlterField(
            model_name='subprogramdisbursement',
            name='voucher_number',
            field=models.CharField(db_index=True, max_length=30, unique=True, verbose_name='رقم سند الصرف'),
        ),
    ]
