# Generated by Django 4.2.25 on 2026-08-09 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Management', '0014_alter_subprogram_allocated_amount_and_more'),
        ('Accounting', '0006_alter_subprogramdisbursement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundreservation',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'حجز مالي', 'verbose_name_plural': 'الحجوزات المالية'},
        ),
        migrations.AlterField(
            model_name='fundreservation',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='موجب = حجز، سالب = تحرير.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='fundreservation',
            name='reference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fundreservation',
            name='source_type',
            field=models.CharField(choices=[('beneficiary', 'محفظة مستفيد'), ('main_program', 'محفظة برنامج رئيسي'), ('sub_program', 'محفظة برنامج فرعي')], max_length=20),
        ),
        migrations.CreateModel(
            name='AllocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('fund_to_main', 'الصندوق → البرنامج الرئيسي'), ('main_to_main', 'برنامج رئيسي → برنامج رئيسي'), ('main_to_sub', 'البرنامج الرئيسي → الفرعي'), ('sub_to_main', 'البرنامج الفرعي → الرئيسي'), ('main_to_fund', 'البرنامج الرئيسي → الصندوق')], max_length=30, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('reference', models.CharField(blank=True, max_length=50, verbose_name='المرجع')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocation_history', to=settings.AUTH_USER_MODEL, verbose_name='تمت بواسطة')),
                ('from_main_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_history_from', to='Management.mainprogram', verbose_name='من البرنامج الرئيسي')),
                ('from_sub_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_history_from', to='Management.subprogram', verbose_name='من البرنامج الفرعي')),
                ('to_main_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_history_to', to='Management.mainprogram', verbose_name='إلى البرنامج الرئيسي')),
                ('to_sub_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocation_history_to', to='Management.subprogram', verbose_name='إلى البرنامج الفرعي')),
            ],
            options={
                'verbose_name': 'سجل تخصيص',
                'verbose_name_plural': 'سجل التخصيصات',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
