# Generated by Django 4.2.25 on 2026-08-17 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0014_alter_subprogram_allocated_amount_and_more'),
        ('Accounting', '0007_alter_fundreservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprogramdisbursement',
            name='is_reversed',
            field=models.BooleanField(default=False, verbose_name='تم عكس العملية'),
        ),
        migrations.AlterField(
            model_name='allocationhistory',
            name='action',
            field=models.CharField(choices=[('fund_to_main', 'الصندوق > البرنامج الرئيسي'), ('main_to_main', 'برنامج رئيسي > برنامج رئيسي'), ('main_to_sub', 'البرنامج الرئيسي > الفرعي'), ('sub_to_main', 'البرنامج الفرعي > الرئيسي'), ('main_to_fund', 'البرنامج الرئيسي > الصندوق')], max_length=30, verbose_name='نوع العملية'),
        ),
        migrations.AlterField(
            model_name='financialsponsorshipallocation',
            name='sponsorship_invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='Accounting.financialsponsorshipinvoice', verbose_name='سند الكفالة المالية'),
        ),
        migrations.AlterField(
            model_name='financialsponsorshipinvoice',
            name='is_custom_plan',
            field=models.BooleanField(default=False, help_text='إذا كانت الخطة أخرى يسمح بإدخال مبلغ ومدة يدويًا.', verbose_name='خطة مخصّصة (أخرى)'),
        ),
        migrations.AlterField(
            model_name='financialsponsorshipinvoice',
            name='sponsor',
            field=models.ForeignKey(help_text='يجب أن يكون نوع الكافل DONOR في النظام.', limit_choices_to={'role': 'donor'}, on_delete=django.db.models.deletion.PROTECT, related_name='sponsorship_invoices', to='Management.profile', verbose_name='الكافل'),
        ),
    ]
