# Generated by Django 4.2.25 on 2026-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounting', '0008_subprogramdisbursement_is_reversed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundreservation',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='fundreservation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fundreservation',
            name='main_program',
        ),
        migrations.RemoveField(
            model_name='fundreservation',
            name='sub_program',
        ),
        migrations.RemoveField(
            model_name='fundtomainprogramallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='fundtomainprogramallocation',
            name='main_program',
        ),
        migrations.RemoveField(
            model_name='maintosubprogramallocation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='maintosubprogramallocation',
            name='main_program',
        ),
        migrations.RemoveField(
            model_name='maintosubprogramallocation',
            name='sub_program',
        ),
        migrations.RemoveField(
            model_name='sponsorshipreport',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='sponsorshipreport',
            name='generated_by',
        ),
        migrations.RemoveField(
            model_name='subprogramdisbursementline',
            name='beneficiary',
        ),
        migrations.RemoveField(
            model_name='subprogramdisbursementline',
            name='disbursement',
        ),
        migrations.AlterField(
            model_name='fundentry',
            name='type',
            field=models.CharField(choices=[('general_donation_income', 'دخل تبرع عام'), ('sponsorship_income', 'دخل كفالة مالية'), ('program_expense', 'صرف على برنامج'), ('adjustment', 'تعديل رصيد')], max_length=40, verbose_name='نوع الحركة'),
        ),
        migrations.DeleteModel(
            name='BeneficiaryBalanceEntry',
        ),
        migrations.DeleteModel(
            name='FundReservation',
        ),
        migrations.DeleteModel(
            name='FundToMainProgramAllocation',
        ),
        migrations.DeleteModel(
            name='MainToSubProgramAllocation',
        ),
        migrations.DeleteModel(
            name='SponsorshipReport',
        ),
        migrations.DeleteModel(
            name='SubProgramDisbursementLine',
        ),
    ]
